# This is used to convert a block to an item, for cases where
# the materials for each differ. (Example: skulls, doors)
block_items:
 black_wall_banner: black_banner
 blue_wall_banner: blue_banner
 brown_wall_banner: brown_banner
 cyan_wall_banner: cyan_banner
 gray_wall_banner: gray_banner
 green_wall_banner: green_banner
 light_blue_wall_banner: light_blue_banner
 light_gray_wall_banner: light_gray_banner
 lime_wall_banner: lime_banner
 magenta_wall_banner: magenta_banner
 orange_wall_banner: orange_banner
 pink_wall_banner: pink_banner
 purple_wall_banner: purple_banner
 red_wall_banner: red_banner
 white_wall_banner: white_banner
 yellow_wall_banner: yellow_banner
 acacia_wall_sign: acacia_sign
 birch_wall_sign: birch_sign
 crimson_wall_sign: crimson_sign
 dark_oak_wall_sign: dark_oak_sign
 jungle_wall_sign: jungle_sign
 oak_wall_sign: oak_sign
 spruce_wall_sign: spruce_sign
 warped_wall_sign: warped_sign
 mangrove_wall_sign: mangrove_sign
 cherry_wall_sign: cherry_sign
 bamboo_wall_sign: bamboo_sign
 acacia_hanging_sign: acacia_sign
 acacia_wall_hanging_sign: acacia_sign
 birch_hanging_sign: birch_sign
 birch_wall_hanging_sign: birch_sign
 crimson_hanging_sign: crimson_sign
 crimson_wall_hanging_sign: crimson_sign
 dark_oak_hanging_sign: dark_oak_sign
 dark_oak_wall_hanging_sign: dark_oak_sign
 jungle_hanging_sign: jungle_sign
 jungle_wall_hanging_sign: jungle_sign
 oak_hanging_sign: oak_sign
 oak_wall_hanging_sign: oak_sign
 spruce_hanging_sign: spruce_sign
 spruce_wall_hanging_sign: spruce_sign
 warped_hanging_sign: warped_sign
 warped_wall_hanging_sign: warped_sign
 mangrove_hanging_sign: mangrove_sign
 mangrove_wall_hanging_sign: mangrove_sign
 cherry_hanging_sign: cherry_sign
 cherry_wall_hanging_sign: cherry_sign
 bamboo_hanging_sign: bamboo_sign
 bamboo_wall_hanging_sign: bamboo_sign
 skeleton_wall_skull: skeleton_skull
 wither_skeleton_wall_skull: wither_skeleton_skull
 creeper_wall_head: creeper_head
 dragon_wall_head: dragon_head
 player_wall_head: player_head
 zombie_wall_head: zombie_head
