train_item:
  item:
    ==: org.bukkit.inventory.ItemStack
    DataVersion: 4325
    id: minecraft:diamond_pickaxe
    count: 1
    components:
      minecraft:custom_model_data: '{floats:[18012.0f]}'
      minecraft:unbreakable: '{}'
      minecraft:custom_name: '{extra:[{bold:0b,color:"green",italic:0b,obfuscated:0b,strikethrough:0b,text:"Steam
        Engine",underlined:0b}],text:""}'
    schema_version: 1
